# Generated by Django 5.2.8 on 2025-11-25 15:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('menu_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Grill', 'Grill'), ('Drinks', 'Drinks')], default='Breakfast', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('dietary_info', models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-Free', 'Gluten-Free'), ('Spicy', 'Spicy'), ('None', 'None')], max_length=50, null=True)),
                ('prep_time', models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('available', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_until', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dishes.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dish_images/')),
                ('alt_text', models.CharField(blank=True, max_length=150, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dishes.dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Portion size (e.g., Small, Medium, Large)', max_length=50)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in grams (optional)', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='dishes.dish')),
            ],
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['slug'], name='dishes_dish_slug_f32b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['name'], name='dishes_dish_name_e93a9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_category_slug'),
        ),
        migrations.AddIndex(
            model_name='dishimage',
            index=models.Index(fields=['dish'], name='dishes_dish_dish_id_cbb33e_idx'),
        ),
        migrations.AddIndex(
            model_name='dishportion',
            index=models.Index(fields=['dish', 'size'], name='dishes_dish_dish_id_9d421c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishportion',
            unique_together={('dish', 'size')},
        ),
    ]
