# Generated by Django 4.2.30 on 2026-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_card',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='dishes/'),
        ),
    ]
