# Generated by Django 5.2.8 on 2025-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_category_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menu_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Grill', 'Grill'), ('Drinks', 'Drinks')], default='Breakfast', max_length=50),
        ),
    ]
