# Generated by Django 4.2.16 on 2025-12-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20251202_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='public_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
