# Generated by Django 4.2.16 on 2025-12-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_email_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='public_tracking',
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
